version: '3.8'
services:
  gateway:
    build: shareIt-gateway
    image: share-it-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://share-it-server:9090

  server:
    build: shareIt-server
    image: share-it-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareitdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  db:
    image: postgres:13.7-alpine
    container_name: postgres-database
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareitdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root